version: '3.8'

services:
  kobifind-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kobifind-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/data/db.json
      - MONGO_URI=${MONGO_URI}
